const  ActionTypes = {
    SET_AQI_DATA: "SET_AQI_DATA",
    CLEAR_AQI_DATA: "CLEAR_AQI_DATA",
    SET_CITY_DETAILS: "SET_CITY_DETAILS",
    CLEAR_CURR_CITY: "CLEAR_CURR_CITY",
    SET_CURRENT_CITY: "SET_CURRENT_CITY"
};

export default ActionTypes;
